"""CI check: verify README numbers match stats.json.

stats.json is the single source of truth, generated by the pipeline.
Figures and this checker both read from it. If any number in the
README doesn't match stats.json, CI fails.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

STATS_PATH = Path("data/processed/stats.json")


def flatten(d: dict, prefix: str = "") -> dict[str, str]:
    """Flatten nested dict into dot-separated key -> string value."""
    out: dict[str, str] = {}
    for k, v in d.items():
        key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            out.update(flatten(v, key))
        else:
            out[key] = str(v)
    return out


def check_readme(stats: dict) -> list[str]:
    """Check README contains key numbers from stats.json."""
    readme = Path("README.md").read_text()
    errors: list[str] = []

    checks = [
        ("dataset.total_prs", f"{stats['dataset']['total_prs']:,}", "Total PRs"),
        ("dataset.n_repos", str(stats["dataset"]["n_repos"]), "Number of repos"),
        ("dataset.n_contributors", f"{stats['dataset']['n_contributors']:,}", "Unique contributors"),
        ("outcomes.merge_rate", str(stats["outcomes"]["merge_rate"]), "Merge rate"),
        ("merge_time.median_hours", str(stats["merge_time"]["median_hours"]), "Median merge time"),
        ("funnel.2nd_pr_pct", str(stats["funnel"]["2nd_pr_pct"]), "Funnel 2nd PR %"),
        ("funnel.dropout_1st_pct", str(stats["funnel"]["dropout_1st_pct"]), "Funnel dropout %"),
        ("tool_eras.agentic.merge_rate", str(stats["tool_eras"]["agentic"]["merge_rate"]), "Agentic merge rate"),
        ("tool_eras.agentic.ft_merge_rate", str(stats["tool_eras"]["agentic"]["ft_merge_rate"]), "Agentic FT merge rate"),
    ]

    for key, expected, label in checks:
        if expected not in readme:
            errors.append(f"  {label} ({key}): expected '{expected}' not found in README")

    return errors


def main() -> None:
    if not STATS_PATH.exists():
        print("SKIP: no stats.json found (run make process first)")
        sys.exit(0)

    with open(STATS_PATH) as f:
        stats = json.load(f)

    print("Checking README against stats.json...")
    print(f"  Source: {STATS_PATH}")
    print(f"  Dataset: {stats['dataset']['total_prs']:,} PRs, {stats['dataset']['n_repos']} repos")

    errors = check_readme(stats)

    if errors:
        print(f"\nFAILED: {len(errors)} number(s) in README don't match stats.json:")
        for e in errors:
            print(e)
        sys.exit(1)
    else:
        print("\nPASSED: all README numbers match stats.json")


if __name__ == "__main__":
    main()
